apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: AUTH0_API_IDENTIFIER
              value: http://gordle-api
            - name: AUTH0_DOMAIN
              value: localhost:4242
          image: server
          livenessProbe:
            exec:
              command:
                - curl -sSf GET localhost:4242/gordle/healthy > /dev/null
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: gordle-server
          ports:
            - containerPort: 4242
          resources: {}
      restartPolicy: Always
status: {}
