version: '3'

tasks:
  clean:
    cmds:
      - cmd: rm cli
        ignore_error: true
      - cmd: rm coverage.out
        ignore_error: true
      - cmd: rm cp.html
        ignore_error: true
  build:
    cmds:
      - task: clean
      - go build -v ./cmd/cli
  test:
    cmds:
      - task: clean
      - go install github.com/cweill/gotests/gotests@latest
      - go test -v ./... -coverprofile=coverage.out
      - go tool cover -html coverage.out -o cp.html
      - cmd: explorer.exe .
        ignore_error: true
  run:
    cmds:
      - task: clean
      - go run ./cmd/cli
  vet:
    cmds:
      - task: clean
      - go vet ./...
