# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install Dependencies
        run: make install

      - name: Build
        run: make build

      - name: Test
        run: make test-ci

      - name: Vet
        run: make vet

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@3440e5ef70c638a9f44602a80ab017feee1309fe
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@a38818475bb21847788496e9f0fddaa4e84955ba
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: 'coverage.out'
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
          force-coverage-parser: 'go'
