name: Go

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dictionary
        run: sudo apt-get install -y wbritish

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build
        run: task build

      - name: Test
        run: task test-ci

      - name: Vet
        run: task vet
